[language-server.csharp]
# cargo install --git https://github.com/SofusA/csharp-language-server
command = "csharp-language-server"

[[language]]
name = "c-sharp"
language-servers = ["csharp"]
file-types = ["cs", "csproj", "sln"]
auto-format = false

[[language]]
name = "json5"
scope = "source.json5"
injection-regex = "json5"
file-types = ["json5", "hjson"]

[[language]]
name = "xml"
formatter = { command = "xmllint", args = ["--format", "-"] }

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
language-servers = [ "pyright" ]

[[language]]
name = "Renode repl"
scope = "source.repl"
comment-tokens = ['//']
file-types = ["repl"]
