[language-server.roslyn]
# cargo install --git https://github.com/SofusA/roslyn-language-server
command = "roslyn-language-server"

[[language]]
name = "c-sharp"
language-servers = ["roslyn"]
file-types = ["cs", "csproj", "sln"]
auto-format = false

[[language]]
name = "xml"
formatter = { command = "xmllint", args = ["--format", "-"] }

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
